### PR TITLE
lxc file command should specify container name

### PR DESCRIPTION
**Pull request by guillaumevincent**
according to the documentation <source> in the case of pull and <target> in the case of push are <container name>/<path>

Signed-off-by: Guillaume Vincent <gvincent@oslab.fr>

### CODE REVIEW

**Comment by stgraber** [comment]
Thanks for this. Can I just ask you to edit your commit message to include the required Signed-off-by line (see CONTRIBUTING.md for details)?

Thanks

**Comment by guillaumevincent** [comment]
done sorry for that

**Comment by stgraber** [comment]
Thanks, applied!

**Comment by guillaumevincent** [comment]
sorry for forgetting

**Pull request closed without merging**
