### PR TITLE
 Added css for tables

### PR DESCRIPTION
**Pull request by toby63**
Signed-off-by: Tobias Gerold <tobias@g3ro.eu>

* adds vertical border lines
* automatic width
* table headers text is bold

### CODE REVIEW

**Comment by toby63** [comment]
To see how it looks in comparison:
[Standard - tables old](https://github.com/toby63/stuff/blob/master/tables.png)
[tables new](https://github.com/toby63/stuff/blob/master/tables-new.png)

**Comment by stgraber** [comment]
Slight issue: https://images.linuxcontainers.org/

**Comment by stgraber** [comment]
And https://linuxcontainers.org/lxd/downloads/ looks horrible too, reverting.

**Comment by stgraber** [comment]
Reverted

**Comment by stgraber** [comment]
Screenshot from 2020-06-02 10-52-50
Screenshot from 2020-06-02 10-52-44

**Comment by toby63** [comment]
Whoops, sry I forgot I use a dark mode in my browser :sweat_smile:.

So I used a colour that is slightly darker than the normal appearance.
So many traps one can fall into...I will change it.

But did you just dislike the colour or other elements as well?

**Comment by stgraber** [comment]
Color was the main issue.

I'm not sure about having borders on all sides, it may be fine for the website but may look weird on e.g the image listing on https://images.linuxcontainers.org where the current style makes it feel less cramped.

**Comment by toby63** [comment]
> I'm not sure about having borders on all sides, it may be fine for the website but may look weird on e.g the image listing on https://images.linuxcontainers.org where the current style makes it feel less cramped.

:thinking: Yes I see what you mean.
Would you approve of the use of different classes?
So we have one table-style here and another table-style there.

I need to test whether that works with markdown files too, but my internet search showed some potential solutions for that (even without using javascript).

An Alternative would be a higher value for `padding`, would that be sufficient?

**Comment by stgraber** [comment]
Yeah, would be interesting to see if a different class can be used for that so we can differentiate between high-density and low-density

**Comment by toby63** [comment]
In think I found something:
https://python-markdown.github.io/extensions/attr_list/

This seems to let one add ids and classes to elements.
I will test this and report back :smiley:.

**Comment by toby63** [comment]
"Bad" news: AttributeList only seems to work for some html elements, such as blocks, links etc.

I found some topics in related software (that use markdown) (for example: https://github.com/jgm/pandoc/issues/684), but I haven't found a good solution yet.

Other alternatives including `div` also don't seem to work, but I will test it some more.

Only alternative that worked so far is using plain html inside a markdown document.
So specific tables would be html-tables.
But thats not so convenient, given the case that other people just want to modify the documentation and website with markdown syntax.

**Pull request merged**
