### PR TITLE
Added some extensions for markdown

### PR DESCRIPTION
**Pull request by toby63**
Signed-off-by: Tobias Gerold <tobias@g3ro.eu>

I added the following markdown extensions:
* Tables
* Footnotes
* Admonition
* Wikilinks

### CODE REVIEW

**Comment by toby63** [comment]
Two Notes:
* Admonition needs some css changes, right now it looks like this:
screenshot of note
It could maybe look like the notes on this site: https://mkdocs.readthedocs.io/en/stable/user-guide/styling-your-docs/#using-the-docs_dir

* Tables: the visual appearance could be improved, right now it looks like this:
screenshot of tables
The following might be modified:
    * the width of the table might be reduced (so it is not stretched to the width of the site)
    * the vertical borders visible
    * the header bold and clearly seperated from the content

**Comment by stgraber** [comment]
Travis doesn't look happy.

```
$ pycodestyle generate && python generate
generate:162:1: W293 blank line contains whitespace
generate:166:1: W293 blank line contains whitespace
generate:168:64: E211 whitespace before '('
generate:170:1: W293 blank line contains whitespace
generate:172:68: E211 whitespace before '('
generate:177:64: E211 whitespace before '('
generate:183:80: E501 line too long (113 > 79 characters)
The command "pycodestyle generate && python generate" exited with 1.
```

**Comment by toby63** [comment]
Yeah the syntax, my most beloved topic in coding...
 Still failing, I will look at it:
```
generate:183:71: W291 trailing whitespace
generate:184:9: E128 continuation line under-indented for visual indent
```

**Comment by toby63** [comment]
I guess I have to rebase the commits :sweat_smile:.

Now it wants the line shorter, `184:80: E501 line too long (92 > 79 characters)`
So I really need to make three lines out of it...doesn't look very good imo, but if it wants that.
Guess I have to setup some travis-like tool for me too.

Btw ones it is fixed, we can delete the comments :smiley:.

**Comment by toby63** [comment]
I will come back later, 
I will setup `pycodestyle` and then rebase the commits.

**Comment by stgraber** [comment]
Travis looks happy but some of the commits aren't signed-off. You may want to also rebase things together a bit to make it easier to review.

**Comment by toby63** [comment]
Done.

**Pull request merged**
