### PR TITLE
Vanilla 1.8

### PR DESCRIPTION
**Pull request by deadlight**
## Done
Updated Vanilla Framework to 1.8 and updated the markup/classes where necessary.

## QA
Run the site locally and click through the pages. 
Check functionality at all viewport sizes (especially the updated nav component)

### CODE REVIEW

**Comment by stgraber** [comment]
@deadlight thanks!

As Jenkins pointed out above, some of your commits (actually looks like all of them) are missing the necessary `Signed-off-by: Firstname Lastname <email>` line. Can you edit your commits and update the branch?

Thanks!

**Comment by deadlight** [comment]
@stgraber Oh, sorry. I had forgotten that this repo required signed commits. I will rewrite the commits and update the branch.

**Comment by anthonydillon** [comment]
Look great @deadlight. All +1 apart from the small QA point below.

## QA
- Go to try-it and the `margin-left: -10px;` on the #tryit_console is causing the terminal text to cut off the first letter

**Comment by deadlight** [comment]
@anthonydillon I've removed the CSS that was causing that issue. Turns out that it wasn't really needed.

**Comment by stgraber** [comment]
You're modifying the main try-it page but not its translations don't those also need updating?

**Comment by anthonydillon** [comment]
The terminal is no longer full width
screenshot_2019-02-13 linux containers - lxd - try it online

**Comment by deadlight** [comment]
@stgraber yes, I will update them. I just want to get a designer to look at the English one first and then I'll duplicate the changes once I've got sign-off from them.

**Comment by deadlight** [comment]
@anthonydillon fixed that issue

**Comment by anthonydillon** [comment]
@deadlight Thanks LGTM :+1:

**Comment by kwm14** [comment]
@deadlight looking good. Design +1 👍

**Comment by deadlight** [comment]
@stgraber design are happy with the updates so I've also converted the Japanese translation of the Try It page.

**Comment by stgraber** [comment]
Hmm, so looks like this regressed try-it a bit: https://linuxcontainers.org/lxd/try-it

Specifically, all line breaks appear to get doubled, try running `lxc version` for example, it should just show:
```
Client version: 3.11
Server version: 3.11
```

Instead, I'm getting:
```
Client version: 3.11

Server version: 3.11

```

**Comment by stgraber** [comment]
@deadlight @anthonydillon

**Comment by anthonydillon** [comment]
@stgraber thanks for the heads up. Fix proposed.

**Pull request merged**
