### PR TITLE
Update getting-started.md

### PR DESCRIPTION
**Pull request by nutterthanos**
C399C1CB-65F3-4965-9939-96E1B5D30810
Ubuntu 14.04LTS is eol for all but people with Ubuntu Advantage.

Changed default recommended ubuntu version for host running as a container host
Signed-off-by: Auzzie Gamer <minecraftitsover90@gmail.com>

### CODE REVIEW

**Comment by stgraber** [comment]
should recommend 18.04 and it'd be great if you could update your commit to include the needed `Signed-off-by` line (`git commit --amend -s`)

**Comment by nutterthanos** [comment]
Uh i don’t have a computer to run git commands

**Comment by stgraber** [comment]
Ok, edit the first comment in this PR to include the Signed-off-by line, that should be sufficient for our needs.

**Comment by nutterthanos** [comment]
Hello

**Pull request merged**
