### PR TITLE
typo defintion

### PR DESCRIPTION
**Pull request by aleon1220**
changed typo in word. definition.
Signed-off-by: Andres LeonRangel aleon1220@hotmail.com

### CODE REVIEW

**Comment by stgraber** [comment]
Thanks!

Could you edit your commit message to sign it off (`Signed-off-by: Firstname Lastname <email>`) line.

This can commonly be done with:
 - git commit --amend -s
 - git push --force

Thanks!

**Comment by aleon1220** [comment]
> Thanks!
> 
> Could you edit your commit message to sign it off (`Signed-off-by: Firstname Lastname <email>`) line.
> 
> This can commonly be done with:
> 
> * git commit --amend -s
> * git push --force
> 
> Thanks!

hi thanks for your answer. I only used the github UI to make the change. 
To do what you suggest: do i need to clone the repo in my local system?
how could i do the signed off step from Github UI?
thanks

**Comment by stgraber** [comment]
Ah, okay. You could do it with the git client but I can also easily do it for you.

Can you just edit this PR's description to include it, then I'll copy/paste it into your commit message and merge this for you.

Thanks!

**Comment by aleon1220** [comment]
> Ah, okay. You could do it with the git client but I can also easily do it for you.
> 
> Can you just edit this PR's description to include it, then I'll copy/paste it into your commit message and merge this for you.
> 
> Thanks!

thanks so much. done. i hope that is the alright way.

**Pull request merged**
