### PR TITLE
demo: move terminal to the bottom

### PR DESCRIPTION
**Pull request by ru-fu**
Move the terminal to the bottom of the page and make it sticky.

Signed-off-by: Ruth Fuchss <ruth.fuchss@canonical.com>

### CODE REVIEW

**Comment by ru-fu** [comment]
A bit unsure if we should keep the footer in the demo or if we can/should get rid of it ...

**Comment by stgraber** [comment]
Yeah, we need to either nuke the footer entirely (fine with me) or we need to include it under the terminal. Having it scroll past like it does now looks quite weird :)

**Comment by stgraber** [comment]
For those who can't easily build and run locally, here's what the PR currently looks like.

Screenshot from 2021-08-23 15-07-56
Screenshot from 2021-08-23 15-08-00

**Comment by ru-fu** [comment]
Updated to hide the footer.
Also fixed the terminal width so it works in the mobile view as well.

**Comment by stgraber** [comment]
@ru-fu nice, looks good to me here!

**Comment by stgraber** [comment]
@ru-fu your PR is in marked as Draft so I'll wait until you mark it as ready for review to merge it.

**Comment by ru-fu** [comment]
Rebased and tested in combination with the other update - should be ready now. :)

**Comment by stgraber** [comment]
Thanks!

**Pull request merged**
