### PR TITLE
Logic to detect out of date translations #415

### LINKED ISSUE #415: Add logic to detect out of date translations
We should automatically print a header warning with a link to the english version when the matching translated markdown file is older than the source english version.

### PR DESCRIPTION
**Pull request by anirudh-goyal**
Fixes #415 

- Added support for comparing a translated markdown file and its matching source file based on their last modified times. 
- Translated files are detected based on the `language_prefix` and if they're of the form `foo.<language_prefix>.md`. Its corresponding source file is then `foo.md`.
- If the translated file is more than a day older than source file, a warning is displayed with a link to the English version. 
- To display the warning, the markdown content is changed in Python (without changing the actual markdown file) before calling `md2html` .

Example warning:
image

Signed-off-by: Anirudh Goyal <anirudhgoyal@utexas.edu>

### CODE REVIEW

**Comment by tenforward** [comment]
Hi! I am a translator to Japanese. :-)

I think it's a good concept pull request. But I'm curious about the following:

* Git does not manage a timestamps, so can we detect that the translation is outdated by comparing the local mtime?
* Wouldn't it be better for the outdated messages to be in their own language, rather than English?
* Usually the translation is not available immediately after a original document is updated. I think one day is too short a time limit to consider a translation as old. I think it would be nice if this value could be customized.

**Comment by anirudh-goyal** [comment]
Hello! Thanks for the quick review and the feedback! My responses to your points:

- Oh you're right. I looked into how to use git commit times instead and discovered a python library [Pydriller](https://pydriller.readthedocs.io/en/latest/) Can I go ahead and use that? Not sure if we have some standards for using other libraries.
- I was wondering about that too, but I put it off for now considering that eventually the source version would only be useful to the reader if they can read English. (So if they can't read the English warning, the English version is probably not useful anyway.) Let me know what you think!
- Sure, that's a variable inside a function in `generate`. What's a more appropriate buffer time?

**Comment by stgraber** [comment]
Given the way we generate the website on the server, it should be fine to just look at mtime.
This wouldn't work if we were working off of a new git clone, but we're not, we're just refreshing an existing on-disk repo every 5min or so. This means in our case, the mtime should be correct at about 5min. This should save us from having to do much more complicated logic through git.

I agree that it would be a good idea to include the message from a translated source.

It'd also be nice if we could style it a tiny bit more. The website is using vanilla as a CSS framework which has a `notification` element that should work well for this: https://vanillaframework.io/docs/examples/patterns/notifications/caution

As for the delay, I agree that one day will be more annoying than anything else. We can bump that to a week I think which is usually enough time for us to get the Japanese translations.

For other languages, right now, they're all extremely out of date, so hopefully the warning will help us get more translations.

**Comment by anirudh-goyal** [comment]
Thanks for the feedback! I've made some changes:

- Added a file `content/translation_warnings.json` that contains translated versions of the text "This translated page may be out of date. To read the latest content, please visit the English version."
- The notes/warnings are now in the translated languages using the above mentioned json.
- Used the vanilla framework `notification` element to show the warning. 
- Changed the buffer time to 7 days. 
- I have continued using Python mtime as discussed. 

Here's what it looks like for a Japanese page:

Screen Shot 2020-11-16 at 7 16 52 PM

**Comment by stgraber** [comment]
That's looking quite good!

Just a few things:

 - Missing DCO in commits
 - Syntax error on python3.5 (see Travis link above)
 - I think it would be cleaner to have a WARNINGS.json file including a `outdated-translation` entry in content/ and then have translated version of that file (e.g. WARNINGS.ja.json). This lets us add more similar warnings in the future and better fits the general structure we have. If we can't locate the `WARNINGS.CC.json` file, we fallback to `WARNINGS.json` as we do other files).
 - There is no assumption in our code that the translated and untranslated files are at the same location and just have a `.CC.md` suffix. Instead you should load the `STRUCTURE` file both in translated and untranslated and match the entry based on its `path`. That's the one common property across all translations. Once matched, you can get the path to the markdown from meta->input

**Comment by anirudh-goyal** [comment]
Made some fixes!

Here's how it works now:

- There's WARNINGS.cc.json files with an `outdated-translation` entry as discussed 
- For every markdown file, it first checks if it has a language prefix. If it does, then it loads the STRUCTURE.json of both the translated and untranslated versions and matches the entry based on page_raw_path. If both entries contain a meta->input field, then it compares the `mtime` of those files with a buffer of 7 days.

**Comment by stgraber** [comment]
Looks good, thanks!

I'll pull the branch, do a rebase round and then push it through.

**Pull request merged**
