### PR TITLE
introduction.ru.md

### PR DESCRIPTION
**Pull request by itsNikolay**

### CODE REVIEW

**Comment by techtonik** [comment]
Just want to say that this one is a low quality translation with some obvious spelling errors. =/ So I am not even sure that it is automated translation.

**Comment by stgraber** [comment]
Good to know, hopefully someone can improve this soon.

**Comment by techtonik** [comment]
I can do good translation and technical text review, but not for free, unfortunately.

**Comment by itsNikolay** [comment]
it's just a start, we will improve it :+1:

**Comment by techtonik** [comment]
@itsNikolay good to hear. =)

**Pull request merged**
