### PR TITLE
Replace Bootstrap with Vanilla as the CSS framework 

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Replaced Bootstrap with Vanilla as the CSS framework. Integrated the framework by replacing the components and updating class names.

## QA
- This branch will require an entire site check
- Check the try it page
- Check the different languages work
- Check on small screens

## Details
Fixes https://github.com/ubuntudesign/vanilla-squad/issues/103

### CODE REVIEW

**Comment by stgraber** [comment]
When testing it locally here, the manpages menu entries for lxc, lxcfs and cgmanager don't render properly. They show up as a menu title rather than a browsable sub-menu.

I'm also seeing some text wrapping in the LXD menu, any chance we can get things to render as it used to with bootstrap (no wrapping within the menu)?

**Comment by stgraber** [comment]
Page width also looks much narrower than before causing a bunch of things that didn't wrap before to wrap now, one of the page I looked at for that was the getting started for LXD which now has a bunch of its titles wrapping here.

**Comment by stgraber** [comment]
For the tryit pages, we need to find a different way to handle the different blocks as with the vanilla port, they're now showing up as errors or warnings whereas before we just used the various bootstrap priorities as a way to control the colors.

**Comment by anthonydillon** [comment]
@stgraber Thanks for the feedback. Could you let me know how to generate the man pages locally so I can test the second drop-down menu, please?

**Comment by anthonydillon** [comment]
> For the tryit pages, we need to find a different way to handle the different blocks as with the vanilla port, they're now showing up as errors or warnings whereas before we just used the various bootstrap priorities as a way to control the colors.

Is it the icons in the notification panels that you dislike? I could just remove the icons so we have a tiny coloured border at the top of the notifications?

**Comment by stgraber** [comment]
Yeah, the icons are the problem, I seem to remember the colors looking fine.

**Comment by stgraber** [comment]
For the manpages, you made me realize my local copy was missing them, after copying them from our web server, the menu now renders fine :)

**Comment by stgraber** [comment]
Things look pretty good now. The main issue I can still see is that now that the page width has been extended, the width of the normal text blocks is much larger than we'd like.

So we either need to set a max width for the text separately from the titles (as we don't want those to get wrapped) and then hope the browsers will do a sane job at wrapping stuff, or we need to re-introduce the manual wrapping in the markdown input we had before which this branch removed.

**Comment by anthonydillon** [comment]
Good stuff, Added the body copy wrapping for non-html pages. What do you think?

**Comment by stgraber** [comment]
Looking pretty good here. So just waiting on dropping those icons and then I'll do a full website review.

**Comment by anthonydillon** [comment]
Thanks @stgraber, removed the icons.

**Comment by stgraber** [comment]
tryit looks much better now. One thing I just noticed is that collapsible panels appear to be collapsed by default, at least the try-it instruction one is.

**Comment by stgraber** [comment]
Oh and the commands in the tryit instructions should look like links when you hover otherwise it's not going to be particularly clear to users that clicking them will cause them to be run in the tryit session.

**Comment by stgraber** [comment]
multi-line commands in tryit also appear with a weird indentation for the second line

**Comment by stgraber** [comment]
Looks like you may want to run the website and go through /lxd/try-it and fix the rough edges there :)

**Comment by stgraber** [comment]
There's also something wrong going on with the terminal font in try-it, large tables don't render properly anymore. We need to make sure the font and font size for the terminal isn't changing as the js library used to render the terminal is very very picky about this (due to character to pixel calculation going on in there).

**Comment by anthonydillon** [comment]
@stgraber good spot, I should have gone through the whole thing. (It's really cool by the way). Added some fixes for the try it section. Went through the entire thing and didn't notice any more rough edges.

**Comment by stgraber** [comment]
The step by step instructions still appear folded by default.
I also noticed that the website footer looks messed up.

**Comment by stgraber** [comment]
Otherwise everything looks good, we'll need to strip the forced wrapping from our content, but I have a local commit which does that already, so will just apply on top of your branch when we merge it.

**Comment by stgraber** [comment]
@anthonydillon ping

**Comment by anthonydillon** [comment]
@stgraber sorry have been on a break, on it now.

**Comment by anthonydillon** [comment]
@stgraber I have made the instructions open by default when opening a try it console.

**Comment by anthonydillon** [comment]
What do you mean by the footer looking messed up on the site? Are you seeing the same as the image below? 
linux containers

This matches [Vanilla footer pattern](https://docs.vanillaframework.io/en/patterns/footer).

**Comment by stgraber** [comment]
Hmm, okay, that looks a bit odd after you're used to the current format, but it's not something most people look at so not worth putting too much effort into.

**Comment by stgraber** [comment]
@anthonydillon So looks like I missed a bunch more problems with try-it...

 - The widgets aren't actually collapsible. They show up as a link but clicking just brings you back to the first tab rather than let you toggle visibility. I've removed those links for now, but we do want the instructions and the feedback widget to be collapsible.
 - The feedback widget is completely broken, it doesn't show up when it should (with the last page of instruction) and if I force it to show up, the star rating icons don't show up at all.
 - The font in the terminal is still wrong, causing a bunch of things to wrap when they shouldn't, making it unreadable.

Any chance you can spend some time going through try-it and make it work perfectly again?
This is the most visited page on our website and one of the biggest driver of new users on our end, we really can't have it be broken.

**Comment by stgraber** [comment]
Tweaked our logic for the console a bit which should make it just wide enough for most people to see non-wrapped output.

**Comment by anthonydillon** [comment]
@stgraber thanks for the fixes and sorry for not picking them up when developing. Is that all the issues resolved? If not feel free to file issues and assign me.

**Pull request merged**
