### PR TITLE
generate: Remove cycle from page generator function

### PR DESCRIPTION
**Pull request by techtonik**

### CODE REVIEW

**Comment by stgraber** [comment]
Some of the commits aren't signed-off.

**Comment by stgraber** [comment]
Otherwise the changes look good, thanks.

**Comment by techtonik** [comment]
Too bad it is impossible to edit commits directly from GitHub interface. Need to give legit one more try..

**Comment by techtonik** [comment]
Something is extremely slow - I clone my branch for 20 minutes already. =/

**Comment by techtonik** [comment]
```
$ git clone git://github.com/techtonik/linuxcontainers.org -b patch-1 --depth 10
Cloning into 'linuxcontainers.org'...
remote: Counting objects: 313, done.
remote: Compressing objects: 100% (285/285), done.
Receiving objects:  72% (227/313), 32.25 MiB | 15.00 KiB/s  
```
32Mb @ 15Kb/s  I guess it is tarballs that are guilty.

**Comment by techtonik** [comment]
Rebased and signed off.

**Pull request merged**
