### PR TITLE
Mac specs are wrong

### PR DESCRIPTION
**Pull request by jamielsharief**
Only LXC can be installed on MAC

### CODE REVIEW

**Comment by stgraber** [comment]
No, it's correct. `LXD` here refers to the LXD project (https://github.com/lxc/lxd), the `LXD client` is called `lxc`.
Your change makes it sound like `LXC` itself works on macOS (https://github.com/lxc/lxc) which is most definitely not true.

(Yes, the naming is confusing, sadly it wasn't up to us...)

**Comment by toby63** [comment]
Maybe we could clarify that macos and windows don't include the LXD daemon/server.
I will include it for #412, if thats ok.

**Comment by stgraber** [comment]
Both Windows and macOS currently clearly say `of the LXD client` :)

**Comment by jamielsharief** [comment]
Just re-read, and you are correct, it does say LXD client, hence the confusion.

**Comment by toby63** [comment]
> Both Windows and macOS currently clearly say of the LXD client :)

I also read over it (the first time) (and I know of the whole server/client and LXC vs. LXD stuff, new users likely not), thus my misguided advice to a user in the [forum](https://discuss.linuxcontainers.org/t/installing-lxd-inside-a-docker-container-on-macos/7928/6) (about installing LXD on macos).
So I guess it should be clarified, that LXD (server) runs on Linux only and that it is only possible to manage the linux-containers on a seperate server/computer from macos and windows with the client.
With your approval I might include that in a seperate pull request :slightly_smiling_face:.

**Comment by jamielsharief** [comment]
To be honest, I found the text confusing despite understanding that LXC is not LXD.

**Pull request closed without merging**
