### PR TITLE
Changes to getting-started-cli.md and additions to css

### PR DESCRIPTION
**Pull request by toby63**
I extended and reworked "getting-started-cli.md" a bit and added more css for admonition and "code".

Details:
* local.css:
    * added css for admonition
    * added background-color for "code" in css

* getting-started-cli.md:
    * minor changes to install linux section
    * added admonitions for windows and macos (only client included)
    * specified link to "building from source" on lxd github repo
    * (major change) Extended the "Initial configuration"-section, added a table for configuration options etc.
    *  replaced the warning with an admonition (in Section "Access Control")

For Pictures of the admonition and table, see below.

### CODE REVIEW

**Comment by toby63** [comment]
[Screenshot of Admonition](https://github.com/toby63/stuff/blob/master/admonition.png)
[Screenshot of Table](https://github.com/toby63/stuff/blob/master/table.png)

**Comment by toby63** [comment]
I will change the bottom-padding of the admonition a little bit.
Will rebase then.

**Comment by stgraber** [comment]
Let me know when you're ready for this to be reviewed/merged.

I had a quick look earlier today (before the last 6 commits or so) and it looked quite good to me.

**Comment by toby63** [comment]
@stgraber Ready for Review.

I fixed a little bug, tested it again, so everything should be fine now.

**Comment by toby63** [comment]
I notice a little problem:
`{: .p-noteadm }` is not processed correctly (It's used for the padding inside the admonition)
It needs the [Attribute List-Extension](https://python-markdown.github.io/extensions/attr_list/) in the `generate` file, which I forgot to implement here :sweat_smile:.
I will send a seperate pull request for that later this day.

**Pull request merged**
